### ISSUE TITLE
Crash when connect or disconnect with Bluetooth keyboard.

### ISSUE THREAD

**Issue by yxxone** [plateaukao/browser#14]
W/VideoCapabilities: Unsupported mime video/rvg2
W/VideoCapabilities: Unsupported mime video/flv1
W/VideoCapabilities: Unsupported mime video/wvc1
W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6
I/zygote: Background concurrent copying GC freed 29261(754KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4MB/8MB, paused 575us total 138.725ms
W/VideoCapabilities: Unsupported mime video/wmv1
W/VideoCapabilities: Unsupported mime video/wmv2
W/VideoCapabilities: Unsupported mime video/xvid
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil: HW encoder for video/avc is not available on this device.
E/chromium: [ERROR:gl_surface_egl.cc(289)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
E/cr_ApiBridge: Failed to init handler: Attempt to invoke virtual method 'java.lang.Object java.lang.Class.newInstance()' on a null object reference
I/zygote: Do full code cache collection, code=126KB, data=107KB
I/zygote: After code cache collection, code=122KB, data=76KB
I/zygote: Do partial code cache collection, code=124KB, data=78KB
I/zygote: After code cache collection, code=124KB, data=78KB
    Increasing code cache capacity to 512KB
W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
W/browser: Error loading hosts
W/browser: Error loading hosts
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: info.plateaukao.einkbro, PID: 4690
    kotlin.UninitializedPropertyAccessException: lateinit property ninjaWebView has not been initialized
        at de.baumann.browser.activity.BrowserActivity.initToolbar$lambda-33(BrowserActivity.kt:843)
        at de.baumann.browser.activity.BrowserActivity.lambda$uzL7-qi-cyNo1t90q4XNXWsyAZQ(Unknown Source:0)
        at de.baumann.browser.activity.-$$Lambda$BrowserActivity$uzL7-qi-cyNo1t90q4XNXWsyAZQ.onFocusChange(Unknown Source:2)
        at android.view.View.onFocusChanged(View.java:6962)
        at android.widget.TextView.onFocusChanged(TextView.java:9623)
        at android.widget.AutoCompleteTextView.onFocusChanged(AutoCompleteTextView.java:1119)
        at android.view.View.handleFocusGainInternal(View.java:6634)
        at android.view.View.requestFocusNoSearch(View.java:10875)
        at android.view.View.requestFocus(View.java:10854)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3170)
        at android.view.View.requestFocus(View.java:10821)
        at android.view.View.restoreDefaultFocus(View.java:10800)
        at android.view.ViewGroup.restoreDefaultFocus(ViewGroup.java:3227)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2313)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1411)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6802)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6496)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
I/zygote: Background concurrent copying GC freed 58626(2MB) AllocSpace objects, 1(20KB) LOS objects, 50% free, 6MB/12MB, paused 160us total 154.686ms

**Comment by plateaukao** [comment]
Will try to fix it in next version. Thanks for the issue reporting.

* reference
https://stackoverflow.com/a/18445839/1265915

**Comment by yxxone** [comment]
It works！
