### ISSUE TITLE
Save screenshot doesn't work

### ISSUE THREAD

**Issue by islam2hamy** [plateaukao/browser#18]
Open any site and try (save screenshot)
The app will close

V. : 8.7.6
Miui : 11.0.2

**Comment by plateaukao** [comment]
please use EinkBro to try to download some files. It should ask for external storage permissions. Once permission is granted, you should be able to save screenshots.

**Comment by islam2hamy** [comment]
doesn't work

**Comment by islam2hamy** [comment]
<a href="https://ibb.co/r7h6wg6"><img src="https://i.ibb.co/BzJZCmZ/Screenshot-org-sufficientlysecure-viewer.jpg" alt="Screenshot-org-sufficientlysecure-viewer" border="0"></a>

**Comment by plateaukao** [comment]
@islam2hamy it seems the screenshot is correctly saved, but your default image viewer app to open image is wrong.

**Comment by islam2hamy** [comment]
Where it is saved?

**Comment by plateaukao** [comment]
It's under Pictures/Screenshots.
The same as system screenshot saved place.

**Comment by islam2hamy** [comment]
Not  there

**Comment by plateaukao** [comment]
hm... then I have no idea what might go wrong. 
I verified it on three different devices from different vendors.

**Comment by plateaukao** [comment]
to be clear, the file path may look like this: /storage/emulated/0/Pictures/Screenshots/xxxx.png

**Comment by islam2hamy** [comment]
FATAL EXCEPTION: AsyncTask #3
Process: info.plateaukao.einkbro, PID: 2000
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.NoSuchFieldError: No field DIRECTORY_SCREENSHOTS of type Ljava/lang/String; in class Landroid/os/Environment; or its superclasses (declaration of 'android.os.Environment' appears in /system/framework/framework.jar)
	at de.baumann.browser.e.a.e()
	at de.baumann.browser.e.a.c()
	at de.baumann.browser.e.a.doInBackground()
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by plateaukao** [comment]
@islam2hamy  Thanks for providing the error log! I found out the root cause, and fixed it. It should work fine in next release.

**Comment by plateaukao** [comment]
Hi, @islam2hamy 
The saving screenshot feature should work for your device now (I hope). Please try the latest version: https://github.com/plateaukao/browser/releases/tag/v8.10.1

**Comment by islam2hamy** [comment]
Fixed
Thank you
