### ISSUE TITLE
App crashes at startup

### ISSUE THREAD

**Issue by Kazurin-775** [plateaukao/browser#51]
Logcat:

```
10-15 20:37:27.027  5080  5080 E AndroidRuntime: FATAL EXCEPTION: main
10-15 20:37:27.027  5080  5080 E AndroidRuntime: Process: info.plateaukao.einkbro, PID: 5080
10-15 20:37:27.027  5080  5080 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property ninjaWebView has not been initialized
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at de.baumann.browser.activity.BrowserActivity.initToolbar$lambda-13(BrowserActivity.kt:758)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at de.baumann.browser.activity.BrowserActivity.$r8$lambda$8D4by7gGDdtD2On6E3Vw1gV-xC8(Unknown Source:0)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at de.baumann.browser.activity.BrowserActivity$$ExternalSyntheticLambda5.onFocusChange(Unknown Source:2)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.View.onFocusChanged(View.java:6963)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.widget.TextView.onFocusChanged(TextView.java:9625)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.widget.AutoCompleteTextView.onFocusChanged(AutoCompleteTextView.java:1119)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.View.handleFocusGainInternal(View.java:6635)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.View.requestFocusNoSearch(View.java:10875)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.View.requestFocus(View.java:10854)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3167)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3211)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.requestFocus(ViewGroup.java:3170)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.View.requestFocus(View.java:10821)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.View.restoreDefaultFocus(View.java:10800)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewGroup.restoreDefaultFocus(ViewGroup.java:3227)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2313)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1411)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6802)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:658)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:793)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6496)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
10-15 20:37:27.027  5080  5080 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-15 20:37:27.041  1902  3184 W ActivityManager:   Force finishing activity info.plateaukao.einkbro/de.baumann.browser.activity.BrowserActivity
10-15 20:37:27.049  1902  3184 W ActivityManager:   Force finishing activity cn.modificator.launcher/.Launcher
```

- App version: built from source on the `main` branch, Git revision `c7b5c91` (the release builds on F-Droid or GitHub will generate stack traces with obfuscated symbols)
- Device: Xiaomi Duokan Reader Pro
- OS version: Android 8.1 (build number: MiReaderPro 1.1.8.210610)

**Comment by plateaukao** [comment]
Hi, @Kazurin-775 

I just pushed a fix that might fix this issue. Could you fetch the latest codes and try again to see if it's really fixed? Thank you!

**Comment by plateaukao** [comment]
It should all crash for old versions. Because originally I don't expect any device will enter that line... so there's no implementation for that scenario. Thanks for verifying the fix for me. I'll have a release for this fix. :)
